// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPK34hfFQKcqDomcn_cZbJ4AyzqqsI-N0',
    appId: '1:874931774366:web:b077657b06626585d6ec8f',
    messagingSenderId: '874931774366',
    projectId: 'saksham-flutter-bootcamp-2',
    authDomain: 'saksham-flutter-bootcamp-2.firebaseapp.com',
    storageBucket: 'saksham-flutter-bootcamp-2.appspot.com',
    measurementId: 'G-F4EEH87GJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuC7uTGX9uvs7vxkLYwmv7hJsrRLCkFGM',
    appId: '1:874931774366:android:be4791b7f44442a0d6ec8f',
    messagingSenderId: '874931774366',
    projectId: 'saksham-flutter-bootcamp-2',
    storageBucket: 'saksham-flutter-bootcamp-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRmr0IaW739lU1D73LK3ZH4KG2JqaYfE',
    appId: '1:874931774366:ios:4b1d1e60e51b3aa2d6ec8f',
    messagingSenderId: '874931774366',
    projectId: 'saksham-flutter-bootcamp-2',
    storageBucket: 'saksham-flutter-bootcamp-2.appspot.com',
    iosBundleId: 'com.example.flutterBootcamp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRmr0IaW739lU1D73LK3ZH4KG2JqaYfE',
    appId: '1:874931774366:ios:4b1d1e60e51b3aa2d6ec8f',
    messagingSenderId: '874931774366',
    projectId: 'saksham-flutter-bootcamp-2',
    storageBucket: 'saksham-flutter-bootcamp-2.appspot.com',
    iosBundleId: 'com.example.flutterBootcamp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPK34hfFQKcqDomcn_cZbJ4AyzqqsI-N0',
    appId: '1:874931774366:web:5eb4e0f0884bc54ed6ec8f',
    messagingSenderId: '874931774366',
    projectId: 'saksham-flutter-bootcamp-2',
    authDomain: 'saksham-flutter-bootcamp-2.firebaseapp.com',
    storageBucket: 'saksham-flutter-bootcamp-2.appspot.com',
    measurementId: 'G-WH5J5SHN03',
  );
}
